# @package _global_

defaults:
  - /task/observation/command_long: joint
  - /algo/ppo_roa/module: large
  - override /algo: ppo_roa_train

total_iters: 4000
checkpoint_interval: 1000
upload_interval: 1000

algo:
  freeze_vecnorm: false
  teacher_use_priv: true
  opt: muon
  grad_sync_mode: ddp
  train_amp_dtype: bf16
  policy_lr: 0.0003
  critic_lr: 0.0003
  ppo_epochs: 5
  num_minibatches: 8
  entropy_coef_start: 0.01
  entropy_coef_end: 0.002
  entropy_decay_start: 0.75
  entropy_decay_end: 1.0
  desired_kl: 0.01
  desired_kl_end: 0.005
  reg_coef: 0.2
  reg_warmup_start: 500
  reg_warmup_end: 1000

task:
  num_envs: 8192
